
namePrefix: dev-
commonLabels:
  env: development

commonAnnotations:
  enableFor: developers

images:
- digest: sha256:54c0f4072dbebbfc348167fdc798779a7774ec211188c9d52d3519f764716698
  name: image-registry.openshift-image-registry.svc:5000/book-test/person-service
  newName: quay.io/izderadicka/person-service

configMapGenerator:
- literals:
  - APP_GREETING=We are in super DEVELOPMENT mode
  name: app-config

patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-person-service
  target:
    kind: Route
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
