apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: dev-
commonLabels:
  env: development

commonAnnotations:
  enableFor: developers

images:
- digest: sha256:be1f413d2b015d30265b13a660f44404cb3a590d1325d65ee07fec2fa78faf23
  name: image-registry.openshift-image-registry.svc:5000/book-test/person-service
  newName: quay.io/izderadicka/person-service

configMapGenerator:
- literals:
  - APP_GREETING=We are in super DEVELOPMENT mode
  name: app-config

patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-person-service
  target:
    kind: Route
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
  target:
    kind: Deployment
